build: add pthread dependency to linker flags
Otherwise on Linux the following error occurs during linking:

/bin/ld: libh2o.a(lib_common_memcached.o): undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/bin/ld: libpthread.so.0: error adding symbols: DSO missing from command line